# Generated by Django 2.1.1 on 2018-09-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180819_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='allow_parallel_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
