# Generated by Django 2.0.7 on 2018-07-24 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20180724_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
