# Generated by Django 2.0.7 on 2018-07-24 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180724_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='editable_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
