# Generated by Django 2.0.7 on 2018-07-24 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180724_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tracker.Organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(related_name='administrated_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Administrators'),
        ),
        migrations.AlterField(
            model_name='project',
            name='admins',
            field=models.ManyToManyField(related_name='administrated_projects', to=settings.AUTH_USER_MODEL, verbose_name='Administrators'),
        ),
    ]
