# Generated by Django 2.0.7 on 2018-07-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20180724_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
